###############################################################################
# BASIC AGENT SETTINGS
###############################################################################

# daemon endpoint
agentAddress udp:161

# Identificação do sistema - variáveis do grupo system
sysLocation    "Class Lab — Docker Network Demo"
sysContact     "Costa <admin@lab.local>"
sysName        "docker-linux-router-01"
sysServices    78

###############################################################################
# VIEWS
###############################################################################

#      view          incl/excl    subtree                       mask
view   routerView    included     .1                            80

###############################################################################
# SNMPv3 USER
###############################################################################

createUser snmpadmin SHA "authpass123" AES "privpass123"

###############################################################################
# GROUP + VACM
###############################################################################

#                    sec.model  sec.name
group   adminGroup   usm        snmpadmin

#                 context sec.model sec.level match  read        write  notif
access adminGroup ""      usm       authPriv  exact  routerView  none   none

###############################################################################
# OPTIONAL V2C FOR LAB ONLY
###############################################################################

# isto nao devia existir: apenas para testes no LAB!
rocommunity labpublic 
rocommunity labpublic 127.0.0.1
rocommunity labpublic 10.10.1.0/24
rocommunity labpublic 10.10.2.0/24

###############################################################################
# EXTEND CONFIG
###############################################################################
# Default route via ip route
extend defaultRoute /bin/sh -c "/sbin/ip route show default"
# IP forwarding kernel flag
extend ipForwardingStatus /bin/sh -c "/sbin/sysctl -n net.ipv4.ip_forward"

